name: Docker build and Publish
on:
  push:
    tags:
      - v*

env:
  DEBIAN_RELEASE: buster
  DOCKER_PWD: /root
  DOCKER_IMAGE: debian:${DEBIAN_RELEASE}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/mattermost-enterprise-edition
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MATTERMOST_IMAGE_TAG=${{ github.ref_name }}
            BUILD_NUMBER=${{ github.run_id }}
